### ISSUE TITLE
建议加关键词，而不是只有推送

### ISSUE THREAD

**Issue by liuzj288** [AquamarineCyan/nonebot-plugin-today-in-histroy#1]
比如发送 #历史上的今天  就出来
现在定时推送容易检测出机器人行为封号呢

**Comment by AquamarineCyan** [comment]
> 比如发送 #历史上的今天  就出来
> 现在定时推送容易检测出机器人行为封号呢

后续会加上

**Comment by AquamarineCyan** [comment]
v0.0.4 已加入
直接发送`历史上的今天`即可
