### ISSUE TITLE
[建议]增加所有群定时发送免配置开关，增加用户可自己配置定时发送功能

### ISSUE THREAD

**Issue by itsevin** [AquamarineCyan/nonebot-plugin-today-in-histroy#11]
1. 机器人每次加群都要在配置里面增加群号很麻烦，希望增加所有群定时发送免配置开关
2. 增加用户可自己配置定时发送功能

**Comment by AquamarineCyan** [comment]
>  2. 增加用户可自己配置定时发送功能

是需要分群独立定时吗

**Comment by itsevin** [comment]
就是用户可以自行开启私聊推送功能

**Comment by AquamarineCyan** [comment]
> 就是用户可以自行开启私聊推送功能

用户通过命令控制自己的私聊订阅，去除.env.*的配置限制对吧

**Comment by itsevin** [comment]
是的，结合第一点总结一下就是：可以在配置中开启所有群聊默认推送，可以再加一个群聊推送黑名单机制（可以在聊天中用指令开关，建议群管理员和super user可用）。然后对于私聊用户增加自行开关推送功能。

**Comment by AquamarineCyan** [comment]
已发版
