### ISSUE TITLE
api挂了

### ISSUE THREAD

**Issue by balh55y** [AquamarineCyan/nonebot-plugin-today-in-histroy#2]
![image](https://user-images.githubusercontent.com/85926883/181413705-4949aec1-09c4-46b4-8595-46805310351f.png)

**Comment by AquamarineCyan** [comment]
还真是，周末看看别的接口，如果您有可以在下方提供给我

**Comment by balh55y** [comment]
大事记API地址：https://zhufred.gitee.io/zreader/ht/event/+日期.json

出身和逝世API地址:https://zhufred.gitee.io/zreader/ht/ld/+日期.json

**Comment by balh55y** [comment]
![image](https://user-images.githubusercontent.com/85926883/181418613-2de2b27e-f34f-4f13-b347-d1543803edcf.png)

**Comment by balh55y** [comment]
`async def get_history_info() -> str:
    async with httpx.AsyncClient() as client:
        month = date.today().strftime("%m")
        day = date.today().strftime("%d")
        url1 = f"https://zhufred.gitee.io/zreader/ht/event/{month}{day}.json"
        url2 = f"https://zhufred.gitee.io/zreader/ht/ld/{month}{day}.json"
        r = await client.get(url1)
        r1 = await client.get(url2)
        content = json.loads(r.text)
        content1 = json.loads(r1.text)
        content += content1
        sort_data=sorted(content, key=operator.itemgetter('year'), reverse=False)   #排序
        today = f"{month}月{day}日"
        s = f"历史上的今天 {today}\n"
        for item in sort_data:
            s = s + f"{item['title']}\n"
        print(s)
        return s`
稍微改了下,貌似能用

**Comment by balh55y** [comment]
```python
async def get_history_info() -> str:
    async with httpx.AsyncClient() as client:
        month = date.today().strftime("%m")
        day = date.today().strftime("%d")
        url1 = f"https://zhufred.gitee.io/zreader/ht/event/{month}{day}.json"
        url2 = f"https://zhufred.gitee.io/zreader/ht/ld/{month}{day}.json"
        r = await client.get(url1)
        r1 = await client.get(url2)
        content = json.loads(r.text)
        content1 = json.loads(r1.text)
        content += content1
        sort_data=sorted(content, key=operator.itemgetter('year'), reverse=False)   #排序
        today = f"{month}月{day}日"
        s = f"历史上的今天 {today}\n"
        for item in sort_data:
            s = s + f"{item['title']}\n"
        print(s)
        return s
```
稍微改了下貌似能用

**Comment by AquamarineCyan** [comment]
> ```python
> async def get_history_info() -> str:
>     async with httpx.AsyncClient() as client:
>         month = date.today().strftime("%m")
>         day = date.today().strftime("%d")
>         url1 = f"https://zhufred.gitee.io/zreader/ht/event/{month}{day}.json"
>         url2 = f"https://zhufred.gitee.io/zreader/ht/ld/{month}{day}.json"
>         r = await client.get(url1)
>         r1 = await client.get(url2)
>         content = json.loads(r.text)
>         content1 = json.loads(r1.text)
>         content += content1
>         sort_data=sorted(content, key=operator.itemgetter('year'), reverse=False)   #排序
>         today = f"{month}月{day}日"
>         s = f"历史上的今天 {today}\n"
>         for item in sort_data:
>             s = s + f"{item['title']}\n"
>         print(s)
>         return s
> ```
> 稍微改了下貌似能用
> 

能用的话直接pr就行

**Comment by balh55y** [comment]
提了
