### ISSUE TITLE
【建议】文案修改

### ISSUE THREAD

**Issue by Agnes4m** [AquamarineCyan/nonebot-plugin-today-in-histroy#4]
没看issues真不确定这个是名人逝世年份，建议可以写清楚辣
![image](https://user-images.githubusercontent.com/70925546/182752884-49c43363-fbf6-4085-b398-00ccb9290ae0.png)

**Comment by AquamarineCyan** [comment]
正在测试换源
百度官方api
```
https://baike.baidu.com/cms/home/eventsOnHistory/08.json
```

**Comment by AquamarineCyan** [comment]
> 正在测试换源 百度官方api
> 
> ```
> https://baike.baidu.com/cms/home/eventsOnHistory/08.json
> ```

已换源，更新[v0.0.6](https://github.com/AquamarineCyan/nonebot-plugin-today-in-history/releases/tag/v0.0.6)即可

**Comment by Agnes4m** [comment]
可以在文案开头加个*或者其他什么开头嘛，测试发现两个机器人能互相刷屏‘’

**Comment by AquamarineCyan** [comment]
> 可以在文案开头加个*或者其他什么开头嘛，测试发现两个机器人能互相刷屏‘’

`v0.0.7`已发版，默认采用图片发送

如果仍需要文字版，以`v0.0.6`为例
https://github.com/AquamarineCyan/nonebot-plugin-today-in-history/blob/efa430b8d2a3143e0edd9fee3013d09b92283520/nonebot_plugin_today_in_history/__init__.py#L101
找到插件对应文件，修改上述语句为
```python
s = f"{today} 历史上的今天\n"
```
或其他任意不以`历史上的今天`为开头即可
