### ISSUE TITLE
可以直接生成图片吗

### ISSUE THREAD

**Issue by wayne0926** [AquamarineCyan/nonebot-plugin-today-in-histroy#5]
文字看起来排版有点乱，直接生成图片会不会好点

**Comment by AquamarineCyan** [comment]
测试使用 [nonebot-plugin-txt2img](https://github.com/mobyw/nonebot-plugin-txt2img) 转换，等待 `v0.0.7`

**Comment by AquamarineCyan** [comment]
`v0.0.7`已发版，默认采用图片发送
