### ISSUE TITLE
插件引入失败

### ISSUE THREAD

**Issue by yyyhop** [AquamarineCyan/nonebot-plugin-today-in-histroy#7]
![8JBSHYBD~C@ 3ZUY2 S%IVC](https://user-images.githubusercontent.com/116648878/198635933-40266af7-646a-4990-8503-a4a45a594489.png)
![U2}I%TTCG5H_CTX X)7W)H2](https://user-images.githubusercontent.com/116648878/198636071-7d81a844-9ea9-4442-904d-14dc95c202e7.png)
这样报错是为什么？我插件已经下载了

**Comment by AquamarineCyan** [comment]
插件名为`nonebot_plugin_today_in_history` 均为下划线

**Comment by yyyhop** [comment]
哦哦哦，好的，谢谢！

**Comment by yyyhop** [comment]
> 插件名为`nonebot_plugin_today_in_history` 均为下划线

但是我插件名改对了之后为什么机器人就不运行了？
![K0UQC9S60 06MYJ(EZY _ 4](https://user-images.githubusercontent.com/116648878/198813494-975adfc1-ebd3-4b4d-bee3-3eb1d9e8dcff.png)
![I7ESZD{HZ8(%I_F8_OC0TRG](https://user-images.githubusercontent.com/116648878/198813499-e2364966-7873-4aa2-942a-6e58bde5a608.png)

**Comment by AquamarineCyan** [comment]
> > 插件名为`nonebot_plugin_today_in_history` 均为下划线
> 
> 但是我插件名改对了之后为什么机器人就不运行了？
> ![K0UQC9S60 06MYJ(EZY _ 4](https://user-images.githubusercontent.com/116648878/198813494-975adfc1-ebd3-4b4d-bee3-3eb1d9e8dcff.png)
> ![I7ESZD{HZ8(%I_F8_OC0TRG](https://user-images.githubusercontent.com/116648878/198813499-e2364966-7873-4aa2-942a-6e58bde5a608.png)
> 
> 
> 

疑似引用的`nonebot_plugin_htmlrender`问题，尝试更新一下该插件
