### ISSUE TITLE
图片没有显示汉字

### ISSUE THREAD

**Issue by koking0** [AquamarineCyan/nonebot-plugin-today-in-histroy#9]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/45281765/202089537-9e174b80-b3f9-4350-a8cb-c027431547e8.png">

**Comment by AquamarineCyan** [comment]
提供下`python` `nonebot-plugin-htmlrender` `nonebot-plugin-today-in-history` 的版本号，本插件的图片采用`nonebot-plugin-htmlrender`渲染，可尝试更新该插件至最新版

**Comment by koking0** [comment]
插件都是最新版了
nonebot-plugin-today-in-history 0.0.8
nonebot-plugin-htmlrender       0.2.0.1

Python版本：3.9.0

**Comment by AquamarineCyan** [comment]
只有中文不显示应该是字体问题

参考 [nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender) 的说明，尝试在`.env`中修改为使用`firefox`，如果还存在中文字体无法显示，可在 [nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender/issues) 插件提issus
```
# 默认情况 可不写
htmlrender_browser = "chromium"
# 使用 firefox
htmlrender_browser = "firefox"
```
